version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.db
    ports: 
      - "5432:5432"

  api: 
    build: .
    ports:
      - "4000:8000"
    env_file:
      - .env.api
    depends_on:
      - db

volumes:
  postgres_data:
  
