version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.db
    ports: 
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  api: 
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env.api
    depends_on:
        db:
          condition: service_healthy

volumes:
  postgres_data:
  
